### ISSUE TITLE
Error detectet in system binary

### ISSUE THREAD

**Issue by cadgiru** [youshengCode/IfcToolbox#3]
Get 'Error detected in system binary, try refreshing the PC to fix the problem'
![image](https://user-images.githubusercontent.com/42599252/135211642-00ced3de-7977-4508-b892-fe5519ba5a90.png)

**Comment by youshengCode** [comment]
@fadelm0 Currently, to be honest, I haven't found any hack to solve this problem. It is designed like this.

Because in fact, the UWP application (the native win10 application in the Microsoft store) is to avoid the old exe problem.
For the exe application, there is no file permission control, and any application has the permission to read and write various files. Uninstallation is not clean, and installation and update are complicated.

For UWP applications, they are all opposites. For each file, we need to ask the user to grant permission (select the file through the system file selector) every time. We only write our cache files in our own space. When you uninstall the application, all removed and all clean. This is what we want. We think this is also a better experience for our users.

So, sorry we couldn't provide a solution for now. Maybe you need to wait for the portable version.

**Comment by fadelm0** [comment]
@youshengCode I finally tested the IFC convert function on my home PC, where I have full admin rights and it does not work. I get the same error message as above. Is there any generated output log information that would be helpful to you?

**Comment by youshengCode** [comment]
@fadelm0 Thanks very much, We have no other idea about this issue until now. But we will look into it again, I will leave this issue open, hope I can give you some reply next week.

**Comment by youshengCode** [comment]
Hi everyone, IFC Toolbox version 1.2.0 is online. And at the same time, we made a sideload package for people who can't use Microsoft Store. I have run some tests in different machines with this sideload package, seems it works fine to pass this background exe binary error.
 
Here is the release page. https://github.com/youshengCode/IfcToolbox/releases/tag/sideload

I will close this issue and please let me know if you still have the same error. Thank you guys for your feedback.

**Comment by fadelm0** [comment]
Hi @youshengCode. I still get the same error on my work pc. Will test later on my home pc as well.
In the process of testing I also uncovered another bug by mistake, which I will post in a separate issue.

**Comment by youshengCode** [comment]
@fadelm0 Please tell me you are using the sideload package or the new version from microsoft store? I have tested the sideload package with 5 different PC, even some PC bought in 2013. Try the sideload package first, also maybe try in another PC. Sometimes it's really the configuration of PC that blocked all this.
